"""Writes core/src/entities.rs from Python's own html.unescape tables, so
the core decodes a dealer's description exactly as the CLI's scraper did:
python3 core/tools/gen_entities.py"""
import html
import html.entities
from pathlib import Path



def esc(s: str) -> str:
    return "".join(c if 32 <= ord(c) < 127 and c not in '\\"' else f"\\u{{{ord(c):x}}}" for c in s)

named = sorted(html.entities.html5.items())
invalid = sorted(html._invalid_charrefs.items())
out = ["//! Generated by core/tools/gen_entities.py from Python's html.entities.html5",
       "//! and html._invalid_charrefs / _invalid_codepoints; do not edit.", "",
       f"pub static NAMED: [(&str, &str); {len(named)}] = ["]
out += [f'    ("{esc(k)}", "{esc(v)}"),' for k, v in named]
out += ["];", "", f"pub static INVALID_CHARREFS: [(u32, &str); {len(invalid)}] = ["]
out += [f'    ({k}, "{esc(v)}"),' for k, v in invalid]
out += ["];", "", "pub fn invalid_codepoint(n: u32) -> bool {",
        "    INVALID_CODEPOINTS.binary_search(&n).is_ok()", "}", "",
        f"static INVALID_CODEPOINTS: [u32; {len(html._invalid_codepoints)}] = ["]
out += ["    " + ", ".join(str(c) for c in sorted(html._invalid_codepoints)) + ","]
out += ["];", ""]
Path(__file__).resolve().parents[1].joinpath("src", "entities.rs").write_text("\n".join(out))
